### ISSUE TITLE
catch up with Yawning's repo?

### ISSUE THREAD

**Issue by kalikaneko** [OperatorFoundation/obfs4#1]
I've been comparing yawning's repo since this and his diverged, and I think at least this commit could be cherry-picked:
https://github.com/Yawning/obfs4/commit/1a6129b66ff3e66c347b54fbae203c1c61d12d74

**Comment by blanu** [comment]
Thank you for your interest in the project!

I believe that Yawning's repository was switched to an incompatible license, so cherry-picking patches would not be an option. Additionally, the purpose of our repo is to provide support for what you might call "classic" obfs4 and not any new specific variants.

However, if you have a specific feature which you think is lacking or would be beneficial, please feel free to file an issue or submit a patch (of your own creation).

Thank you!

**Comment by kalikaneko** [comment]
hi @blanu - 
pity about the license, I'll have a look.

I will open a new issue then. If I was pin-pointing that specific commit, is because it was a response to Frolov's observation about probe-resistance in obfs4, which I think it's important.

Since it's not so many lines, I will rename variables and obfuscate the patch a bit next time I'm bored then.

**Comment by kalikaneko** [comment]
actually, no, I don't understand the problem with the license, can you clarify?

https://github.com/OperatorFoundation/obfs4/blob/master/LICENSE
https://github.com/Yawning/obfs4/blob/master/LICENSE

**Comment by Yawning** [comment]
> Since it's not so many lines, I will rename variables and obfuscate the patch a bit next time I'm bored then.

Yes, my repository includes (and imports) code that is AGPLed.  No, it does not apply to the vast majority of repository, or the patch in question for that matter.  So just cherry pick it, the patch and the file in question is released under the BSD license.

As a side note, instead of "I will rename variables and obfuscate the patch", the next time there are questions like this about licensing, I have something called an e-mail address.

**Comment by blanu** [comment]
My understanding was that obfs4 switched to GPLv3. Perhaps I was confused about which code is licenses in what way.

I see two licenses in the obfs4 repo:
https://github.com/Yawning/obfs4/blob/master/LICENSE-GPL3.txt
https://github.com/Yawning/obfs4/blob/master/LICENSE

If the code in question is not covered by the GPLv3 license then a patch should be fine.

On the subject of obfuscating patches by changing variable names, this would not change the license of the patch as it is still a derivative work and would retain the same license and so we would not accept such an obfuscated patch if it were derived from code with an incompatible license.

**Comment by kalikaneko** [comment]
https://gitlab.com/yawning/obfs4/-/issues/5#note_573104796 clarifies it.

>  so we would not accept such an obfuscated patch if it were derived from code with an incompatible license

yep, understandable. I was only half joking. can you cherry pick it (it's about 5 lines), or do you prefer if I open a mr?

**Comment by blanu** [comment]
Thank you, this clarifies the situation greatly!

Please submit a pull request.

Thanks for the help!
